//! Build the exact calldata an Ethereum contract needs to read Peregrine state.
//!
//! ```bash
//! cargo run -p peregrine-interop --example evm_calldata
//! ```
//!
//! This runs a real Peregrine table store, real ed25519 validators, and the
//! real checkpoint + inclusion verification — everything except the proving
//! step, which needs the SP1 toolchain and Docker (see the README). What it
//! prints is the `publicValues` argument to `verifyPeregrineState`, byte for
//! byte, plus the three pins a deployment must be configured with.
//!
//! The point is to make the interface concrete without requiring a 20-minute
//! prover run: if you are integrating, this is the shape of the data, and it is
//! generated by the same encoder the guest commits.

use peregrine_core::{Keypair, ValidatorId};
use peregrine_data::tables::{TableId, TableStore};
use peregrine_interop::peregrine::{sign_checkpoint, CommitteeDigest, SignedCheckpoint};
use peregrine_interop::state::{encode_state_journal, StateWitness};
use peregrine_interop::Checkpoint;
use rand::rngs::StdRng;
use rand::SeedableRng;

const PEREGRINE_CHAIN_ID: u64 = 4242;

fn main() {
    // ── a Peregrine network, in miniature ────────────────────────────────────
    // Fixed seed so this example prints the same thing every run; a real
    // validator's keys come from the key ceremony, never from a seeded RNG.
    let mut rng = StdRng::seed_from_u64(0x9E57_1234_ABCD_0001);
    let keys: Vec<Keypair> = (0..4).map(|_| Keypair::generate(&mut rng)).collect();
    let committee = CommitteeDigest {
        epoch: 1,
        validators: keys
            .iter()
            .enumerate()
            .map(|(i, k)| (ValidatorId(i as u16), k.public(), 100u64))
            .collect(),
    };

    // ── some committed state ────────────────────────────────────────────────
    let table = TableId::named("contract.answers");
    let key = b"meaning".to_vec();
    let mut store = TableStore::new();
    store.insert(table, key.clone(), 42u64.to_le_bytes().to_vec());
    let read = store.prove_read(table, &key).expect("row exists");

    // ── a checkpoint, signed by a quorum ────────────────────────────────────
    let checkpoint = Checkpoint {
        round: 99,
        store_root: store.store_root(),
    };
    // Three of four validators — 300 of 400 stake, past the 2/3 threshold.
    // Two would not be enough, and `verify` below would refuse.
    let signatures = keys
        .iter()
        .take(3)
        .enumerate()
        .map(|(i, k)| (ValidatorId(i as u16), sign_checkpoint(k, &checkpoint)))
        .collect();

    let witness = StateWitness {
        chain_id: PEREGRINE_CHAIN_ID,
        committee: committee.clone(),
        signed: SignedCheckpoint {
            checkpoint,
            signatures,
        },
        read,
    };

    // ── verify, and derive the journal ──────────────────────────────────────
    // This is the same function the guest runs inside the zkVM. Running it here
    // proves the witness is sound; running it in the guest proves it to someone
    // who does not trust us.
    let journal = witness.verify().expect("witness verifies");
    let public_values = encode_state_journal(&journal);

    println!("── deployment pins ─────────────────────────────────────────────");
    println!("PEREGRINE_CHAIN_ID = {}", journal.chain_id);
    println!(
        "COMMITTEE_DIGEST   = 0x{}",
        hex::encode(journal.committee_digest.0)
    );
    println!("PROGRAM_VKEY       = <vkey of YOUR build of peregrine-state-guest>");
    println!();
    println!("── the statement ───────────────────────────────────────────────");
    println!("round      : {}", journal.round);
    println!("store root : 0x{}", hex::encode(journal.store_root.0));
    println!("table      : 0x{}", hex::encode(journal.table.0 .0));
    println!("key hash   : 0x{}", hex::encode(journal.key_hash.0));
    println!(
        "value      : 0x{} ({} bytes → {})",
        hex::encode(journal.value),
        journal.value_len,
        u64::from_le_bytes(
            journal.value[32 - journal.value_len as usize..]
                .try_into()
                .unwrap_or([0; 8])
        )
    );
    println!();
    println!("── calldata ────────────────────────────────────────────────────");
    println!("verifyPeregrineState(");
    println!("  publicValues = 0x{}", hex::encode(&public_values));
    println!("  proofBytes   = <SP1 Groth16 proof of the state guest>");
    println!(");");
    println!();
    println!(
        "publicValues is {} bytes = 8 static words.",
        public_values.len()
    );
    println!();
    println!("Then, on Ethereum:");
    println!(
        "  client.getLatestUint(0x{}…, 0x{}…) == 42",
        hex::encode(&journal.table.0 .0[..4]),
        hex::encode(&journal.key_hash.0[..4])
    );
    println!();
    println!("⚠️  The proof is the part that makes any of this trustworthy, and");
    println!("    generating it needs the SP1 toolchain and Docker. Without it");
    println!("    these are just bytes — see contracts/README.md.");
}
