//! **The end-to-end proof.** Generates a real SP1 **Groth16** proof of a
//! Peregrine state read and writes it as a fixture the Solidity test verifies
//! against SP1's actual on-chain verifier.
//!
//! Everything else about the EVM verifier is tested with a mock, because the
//! contract's acceptance *rules* are pure logic. This closes the loop: the
//! bytes a contract would receive in production are produced here, by the real
//! prover, from the real guest.
//!
//! Groth16 rather than Compressed because SP1's on-chain verifier accepts
//! Groth16 (or PLONK) only — and Groth16's trusted setup is the cost of
//! verifying on an EVM at all. See the README's trust notes.
//!
//! Requires the state guest ELF, a Linux/macOS/WSL2 toolchain, **and Docker**
//! (SP1 v6 shells out to `docker` for the gnark wrap step; there is no
//! non-Docker path):
//!
//! ```bash
//! cd crates/peregrine-state-guest && cargo prove build
//! PEREGRINE_STATE_GUEST_ELF=<elf> PEREGRINE_WRITE_FIXTURES=1 \
//!   cargo test -p peregrine-interop --features sp1 --test state_groth16 \
//!   -- --ignored --nocapture
//! ```
//!
//! Proving takes many minutes, so this is not part of the default suite — it is
//! the slow, high-assurance check.
#![cfg(feature = "sp1")]

use peregrine_core::{Hash, Keypair, ValidatorId};
use peregrine_data::tables::{TableId, TableStore};
use peregrine_interop::peregrine::{sign_checkpoint, CommitteeDigest, SignedCheckpoint};
use peregrine_interop::sp1_backend::Guest;
use peregrine_interop::state::StateWitness;
use peregrine_interop::{Checkpoint, Sp1Mode, Sp1Prover};
use rand::rngs::StdRng;
use rand::SeedableRng;

const CHAIN: u64 = 4242;
const ROUND: u64 = 99;

/// The same witness the pure tests use, built from the same seed, so the
/// journal this proof commits is the one `state_journal.rs` already pins.
fn witness() -> StateWitness {
    let mut rng = StdRng::seed_from_u64(0x9E57_1234_ABCD_0001);
    let keys: Vec<Keypair> = (0..4).map(|_| Keypair::generate(&mut rng)).collect();
    let committee = CommitteeDigest {
        epoch: 1,
        validators: keys
            .iter()
            .enumerate()
            .map(|(i, k)| (ValidatorId(i as u16), k.public(), 100u64))
            .collect(),
    };

    let table = TableId::named("contract.answers");
    let key = b"meaning".to_vec();
    let mut store = TableStore::new();
    store.insert(table, key.clone(), 42u64.to_le_bytes().to_vec());
    let read = store.prove_read(table, &key).expect("row exists");

    let checkpoint = Checkpoint {
        round: ROUND,
        store_root: store.store_root(),
    };
    let signatures = keys
        .iter()
        .take(3) // 300 of 400 stake — a quorum
        .enumerate()
        .map(|(i, k)| (ValidatorId(i as u16), sign_checkpoint(k, &checkpoint)))
        .collect();

    StateWitness {
        chain_id: CHAIN,
        committee,
        signed: SignedCheckpoint {
            checkpoint,
            signatures,
        },
        read,
    }
}

#[test]
#[ignore = "needs Docker and takes many minutes"]
fn a_real_groth16_proof_of_peregrine_state() {
    let witness = witness();

    // Check natively first. A failing witness would just panic the guest with
    // no explanation, and distinguishing "my witness is bad" from "proving is
    // broken" after a 20-minute wait is miserable.
    let native = witness.verify().expect("witness verifies natively");

    let prover =
        Sp1Prover::for_guest(Guest::State, Sp1Mode::Groth16).expect("state guest ELF available");

    eprintln!("proving (Groth16 — this takes many minutes)…");
    let t0 = std::time::Instant::now();
    let proof = prover.prove_state(&witness).expect("proving succeeds");
    eprintln!("proved in {:.1?}", t0.elapsed());

    // The guest and the host must agree on the statement. This is the check
    // that would catch a guest built from different source than the host runs.
    assert_eq!(
        proof.journal, native,
        "guest and host must agree on the statement"
    );
    assert_eq!(proof.journal.chain_id, CHAIN);
    assert_eq!(proof.journal.round, ROUND);
    assert_eq!(&proof.journal.value[24..], &42u64.to_le_bytes());

    eprintln!("image id     : 0x{}", hex::encode(proof.image_id));
    eprintln!("public values: {} bytes", proof.public_values.len());
    eprintln!("proof bytes  : {}", proof.proof_bytes.len());

    let fixture = serde_json::json!({
        "_comment": "REAL SP1 Groth16 proof generated by peregrine-interop \
                     tests/state_groth16.rs. Verified on-chain by \
                     contracts/test/PeregrineProofE2E.t.sol against SP1's real \
                     verifier. Regenerate with PEREGRINE_WRITE_FIXTURES=1.",
        "programVKey": format!("0x{}", hex::encode(proof.image_id)),
        "committeeDigest": format!("0x{}", hex::encode(proof.journal.committee_digest.0)),
        "storeRoot": format!("0x{}", hex::encode(proof.journal.store_root.0)),
        "table": format!("0x{}", hex::encode(proof.journal.table.0 .0)),
        "keyHash": format!("0x{}", hex::encode(proof.journal.key_hash.0)),
        "chainId": proof.journal.chain_id,
        "round": proof.journal.round,
        "value": format!("0x{}", hex::encode(proof.journal.value)),
        "valueLen": proof.journal.value_len,
        "expectedUint": 42,
        "publicValues": format!("0x{}", hex::encode(&proof.public_values)),
        "proofBytes": format!("0x{}", hex::encode(&proof.proof_bytes)),
    });
    let text = serde_json::to_string_pretty(&fixture).unwrap() + "\n";
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/test/fixtures/groth16-proof.json"
    );

    if std::env::var("PEREGRINE_WRITE_FIXTURES").is_ok() {
        std::fs::create_dir_all(std::path::Path::new(path).parent().unwrap()).unwrap();
        std::fs::write(path, &text).unwrap();
        eprintln!("wrote {path}");
    } else {
        eprintln!("(set PEREGRINE_WRITE_FIXTURES=1 to update {path})");
    }

    // Sanity: the key hash is the tree position of the key we actually read.
    assert_eq!(proof.journal.key_hash, Hash::digest(b"meaning"));
}
