// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {PeregrineLightClient, ISP1Verifier} from "../src/PeregrineLightClient.sol";
import {SP1Verifier} from "../lib/sp1-contracts/v6.1.0/SP1VerifierGroth16.sol";

/// @title  End-to-end: a real Groth16 proof, verified by SP1's real verifier
///
/// @notice **Nothing is mocked here.** The proof was generated by the actual
///         `peregrine-state-guest` running under SP1, over a real Peregrine
///         table store and four real ed25519 validator signatures. It is
///         checked by SP1's own `SP1VerifierGroth16` (vendored at the exact
///         circuit version that produced it), which does the full BN254 pairing
///         on-chain.
///
/// @dev Every other test in this suite substitutes a mock verifier, because the
///      contract's *rules* are pure logic and generating a Groth16 proof per
///      case would take days. This one exists to establish the thing those
///      tests must assume: that the bytes a prover produces are the bytes this
///      contract can consume, end to end, with no adapter in between.
///
///      Regenerate the fixture with:
///      ```bash
///      cd crates/peregrine-state-guest && cargo prove build
///      PEREGRINE_STATE_GUEST_ELF=<elf> PEREGRINE_WRITE_FIXTURES=1 \
///        cargo test -p peregrine-interop --features sp1 --test state_groth16 \
///        -- --ignored --nocapture
///      ```
contract PeregrineProofE2ETest is Test {
    PeregrineLightClient internal client;
    SP1Verifier internal verifier;

    bytes internal publicValues;
    bytes internal proofBytes;
    bytes32 internal programVKey;
    bytes32 internal committeeDigest;
    bytes32 internal storeRoot;
    bytes32 internal table;
    bytes32 internal keyHash;
    bytes32 internal value;
    uint64 internal chainId;
    uint64 internal round;
    uint64 internal valueLen;
    uint64 internal treeVersion;
    uint256 internal expectedUint;

    /// Path to the generated proof. Absent on a fresh checkout: generating it
    /// needs the SP1 toolchain and Docker, so it is not something every
    /// contributor can reproduce on demand.
    string internal constant FIXTURE = "test/fixtures/groth16-proof.json";

    function setUp() public {
        // Skip loudly, never silently. A skipped end-to-end test that looks
        // like a passing one is worse than a failing one — it reports coverage
        // the suite does not have.
        if (!vm.exists(FIXTURE)) {
            emit log_string(
                "SKIPPED: test/fixtures/groth16-proof.json is absent, so the real-proof "
                "path is NOT covered by this run. Generate it with `cargo prove build` in "
                "crates/peregrine-state-guest, then PEREGRINE_WRITE_FIXTURES=1 cargo test "
                "-p peregrine-interop --features sp1 --test state_groth16 -- --ignored. "
                "Requires Docker: SP1 v6 shells out to it for the gnark wrap step."
            );
            vm.skip(true);
            return;
        }
        string memory raw = vm.readFile(FIXTURE);

        publicValues = vm.parseJsonBytes(raw, ".publicValues");
        proofBytes = vm.parseJsonBytes(raw, ".proofBytes");
        programVKey = vm.parseJsonBytes32(raw, ".programVKey");
        committeeDigest = vm.parseJsonBytes32(raw, ".committeeDigest");
        storeRoot = vm.parseJsonBytes32(raw, ".storeRoot");
        table = vm.parseJsonBytes32(raw, ".table");
        keyHash = vm.parseJsonBytes32(raw, ".keyHash");
        value = vm.parseJsonBytes32(raw, ".value");
        chainId = uint64(vm.parseJsonUint(raw, ".chainId"));
        round = uint64(vm.parseJsonUint(raw, ".round"));
        valueLen = uint64(vm.parseJsonUint(raw, ".valueLen"));
        treeVersion = uint64(vm.parseJsonUint(raw, ".treeVersion"));
        expectedUint = vm.parseJsonUint(raw, ".expectedUint");

        verifier = new SP1Verifier();
        client = new PeregrineLightClient(
            address(verifier), programVKey, committeeDigest, chainId, treeVersion
        );
    }

    /// **The headline test.** A real proof, checked by the real verifier, is
    /// what puts Peregrine state into an Ethereum contract — and nothing else
    /// does.
    function test_ARealGroth16ProofIsAccepted() public {
        uint256 gasBefore = gasleft();
        bytes32 got = client.verifyPeregrineState(publicValues, proofBytes);
        emit log_named_uint("gas for verify + record", gasBefore - gasleft());

        assertEq(got, value, "the proven value");
        assertEq(client.latestRound(), round, "round recorded");
        assertEq(client.latestStoreRoot(), storeRoot, "root recorded");

        (bytes32 v, uint64 len) = client.getVerifiedValue(storeRoot, table, keyHash);
        assertEq(v, value);
        assertEq(len, valueLen);

        // Peregrine wrote a little-endian u64; a consumer gets the number the
        // Rust side meant.
        assertEq(client.getLatestUint(table, keyHash), expectedUint, "42");
    }

    /// **Tampering with the statement breaks the proof.** The public values are
    /// bound to the proof by the pairing check, so flipping a single byte of
    /// the journal must fail inside SP1's verifier — not in our contract's
    /// field checks, which never get to run.
    function test_TamperedPublicValuesAreRejected() public {
        bytes memory tampered = publicValues;
        // Byte 6*32+31 is the low byte of `value` — change 42 to 43.
        tampered[6 * 32 + 24] = bytes1(uint8(43));

        vm.expectRevert();
        client.verifyPeregrineState(tampered, proofBytes);

        assertEq(client.latestRound(), 0, "nothing recorded");
    }

    /// A corrupted proof is rejected by the pairing check.
    function test_TamperedProofIsRejected() public {
        bytes memory tampered = proofBytes;
        // Leave the 4-byte selector intact so this fails on the *cryptography*
        // rather than on SP1's cheap selector check — a stronger assertion.
        tampered[10] = bytes1(uint8(tampered[10]) ^ 0x01);

        vm.expectRevert();
        client.verifyPeregrineState(publicValues, tampered);

        assertEq(client.latestRound(), 0, "nothing recorded");
    }

    /// **Image pinning, against a real proof.** The proof is genuine; the
    /// deployment simply expects a different program. It must be refused —
    /// this is the check that makes a proof mean what the contract thinks it
    /// means.
    function test_AProofOfAnotherProgramIsRefused() public {
        bytes32 wrongVKey = bytes32(uint256(programVKey) ^ 1);
        PeregrineLightClient other = new PeregrineLightClient(
            address(verifier), wrongVKey, committeeDigest, chainId, treeVersion
        );

        vm.expectRevert();
        other.verifyPeregrineState(publicValues, proofBytes);
    }

    /// The proof is real, but this deployment trusts a different validator set.
    /// The committee pin is the only thing that can tell those apart.
    function test_AProofFromAnotherCommitteeIsRefused() public {
        PeregrineLightClient other = new PeregrineLightClient(
            address(verifier), programVKey, bytes32(uint256(0xBAD)), chainId, treeVersion
        );

        vm.expectRevert(
            abi.encodeWithSelector(
                PeregrineLightClient.WrongCommittee.selector,
                committeeDigest,
                bytes32(uint256(0xBAD))
            )
        );
        other.verifyPeregrineState(publicValues, proofBytes);
    }

    /// Replaying the same proof is idempotent, not an attack: the fact is
    /// identical, so I4 is satisfied and the call succeeds.
    function test_ReplayingTheSameProofIsHarmless() public {
        client.verifyPeregrineState(publicValues, proofBytes);
        client.verifyPeregrineState(publicValues, proofBytes);
        (bytes32 v,) = client.getVerifiedValue(storeRoot, table, keyHash);
        assertEq(v, value);
    }

    /// Records the on-chain cost of the whole path, so a regression in proof
    /// size or verifier version is visible rather than discovered on mainnet.
    function test_GasCost() public {
        uint256 before = gasleft();
        client.verifyPeregrineState(publicValues, proofBytes);
        uint256 used = before - gasleft();
        emit log_named_uint("total gas", used);
        // Generous ceiling: a Groth16 pairing is ~250k, plus three SSTOREs.
        assertLt(used, 500_000, "verification should stay well under 500k gas");
    }
}
