// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {PeregrineLightClient, ISP1Verifier} from "../src/PeregrineLightClient.sol";

/// @notice A verifier that accepts anything, so these tests exercise *decoding*
///         rather than proof checking.
/// @dev Safe here precisely because these tests never assert that something was
///      rejected for cryptographic reasons — that is `PeregrineLightClient.t.sol`'s
///      job. Here the question is only "do Rust and Solidity read the same bytes
///      the same way".
contract AcceptAll is ISP1Verifier {
    function verifyProof(bytes32, bytes calldata, bytes calldata) external view {}
}

/// @title  Cross-language journal encoding
/// @notice **The bytes in this test were produced by Rust, not by Solidity.**
///
/// @dev The guest commits public values as a hand-written concatenation of
///      nine 32-byte words (a zkVM guest has no business pulling in an ABI
///      encoder). This contract reads them with `abi.decode`. Nothing forces
///      those two to agree, and a disagreement would not fail loudly — it would
///      silently shift every field, so a `round` would be read as a `chainId`
///      and a proof would attest to something other than what it says.
///
///      So the fixture is generated by
///      `cargo test -p peregrine-interop --test state_journal` and decoded
///      here. If either side changes its layout, this test fails.
contract PeregrineJournalAbiTest is Test {
    struct Fixture {
        bytes abiEncoded;
        uint64 chainId;
        bytes32 committeeDigest;
        uint256 expectedUint;
        bytes32 keyHash;
        uint64 round;
        bytes32 storeRoot;
        uint64 treeVersion;
        bytes32 table;
        bytes32 value;
        uint64 valueLen;
    }

    Fixture internal fx;

    function setUp() public {
        string memory raw = vm.readFile("test/fixtures/state-journal.json");
        // Parsed field by field rather than decoding the whole object into the
        // struct. Whole-object decoding maps JSON keys onto struct members by
        // *sorted key order*, so adding a comment field or renaming anything
        // silently shifts every value — precisely the class of bug this test
        // exists to catch, so it must not be possible in the harness itself.
        fx = Fixture({
            abiEncoded: vm.parseJsonBytes(raw, ".abiEncoded"),
            chainId: uint64(vm.parseJsonUint(raw, ".chainId")),
            committeeDigest: vm.parseJsonBytes32(raw, ".committeeDigest"),
            expectedUint: vm.parseJsonUint(raw, ".expectedUint"),
            keyHash: vm.parseJsonBytes32(raw, ".keyHash"),
            round: uint64(vm.parseJsonUint(raw, ".round")),
            storeRoot: vm.parseJsonBytes32(raw, ".storeRoot"),
            table: vm.parseJsonBytes32(raw, ".table"),
            value: vm.parseJsonBytes32(raw, ".value"),
            valueLen: uint64(vm.parseJsonUint(raw, ".valueLen")),
            treeVersion: uint64(vm.parseJsonUint(raw, ".treeVersion"))
        });
    }

    /// Rust's encoder and Solidity's `abi.decode` agree, field for field.
    function test_RustEncodingDecodesInSolidity() public view {
        assertEq(fx.abiEncoded.length, 9 * 32, "journal is nine static words");

        PeregrineLightClient.Journal memory j =
            abi.decode(fx.abiEncoded, (PeregrineLightClient.Journal));

        assertEq(j.chainId, fx.chainId, "chainId");
        assertEq(j.round, fx.round, "round");
        assertEq(j.treeVersion, fx.treeVersion, "treeVersion");
        assertEq(j.committeeDigest, fx.committeeDigest, "committeeDigest");
        assertEq(j.storeRoot, fx.storeRoot, "storeRoot");
        assertEq(j.table, fx.table, "table");
        assertEq(j.key, fx.keyHash, "keyHash");
        assertEq(j.value, fx.value, "value");
        assertEq(j.valueLen, fx.valueLen, "valueLen");
    }

    /// Re-encoding in Solidity reproduces Rust's bytes exactly. This is the
    /// stronger direction: it catches a padding or ordering difference that a
    /// field-by-field decode might tolerate.
    function test_SolidityReEncodingIsByteIdentical() public view {
        PeregrineLightClient.Journal memory j =
            abi.decode(fx.abiEncoded, (PeregrineLightClient.Journal));
        assertEq(abi.encode(j), fx.abiEncoded, "re-encoding must be byte-identical");
    }

    /// The full path: a real Rust-produced journal driven through the contract,
    /// read back, and interpreted as an integer. This is what a consumer
    /// actually does.
    function test_RustJournalFlowsThroughTheContract() public {
        PeregrineLightClient client = new PeregrineLightClient(
            address(new AcceptAll()),
            bytes32(uint256(1)),
            fx.committeeDigest,
            fx.chainId,
            fx.treeVersion
        );

        client.verifyPeregrineState(fx.abiEncoded, hex"");

        (bytes32 v, uint64 len) = client.getVerifiedValue(fx.storeRoot, fx.table, fx.keyHash);
        assertEq(v, fx.value);
        assertEq(len, fx.valueLen);

        // Peregrine wrote a little-endian u64; the contract must hand back the
        // number the Rust side meant, not a byte-swapped one.
        assertEq(client.getLatestUint(fx.table, fx.keyHash), fx.expectedUint, "42, not 3.02e18");
    }

    /// The committee digest in the fixture is a *real* digest over four real
    /// ed25519 keys. A deployment pinning a different one must reject it, which
    /// is the check that makes the pin worth anything.
    function test_AWrongCommitteePinRejectsTheRealJournal() public {
        PeregrineLightClient client = new PeregrineLightClient(
            address(new AcceptAll()),
            bytes32(uint256(1)),
            bytes32(uint256(0xBAD)),
            fx.chainId,
            fx.treeVersion
        );
        vm.expectRevert(
            abi.encodeWithSelector(
                PeregrineLightClient.WrongCommittee.selector,
                fx.committeeDigest,
                bytes32(uint256(0xBAD))
            )
        );
        client.verifyPeregrineState(fx.abiEncoded, hex"");
    }
}
