//! Generate the cross-language proof fixture consumed by the JS SDK's tests.
//!
//! The JS light-client verifier reimplements Peregrine's Merkle/SMT proof
//! checking in TypeScript. That reimplementation is only trustworthy if it
//! agrees with the Rust one *byte for byte*, so we emit real proofs here and
//! let the TS test suite verify them.
//!
//! Run: `cargo run -p peregrine-node --example gen_js_fixture`

use peregrine_data::tables::{TableId, TableStore};
use serde_json::json;
use std::path::PathBuf;

fn main() -> anyhow::Result<()> {
    let mut store = TableStore::new();

    // Two tables so the store-level Merkle proof has real siblings, and enough
    // rows that the sparse-Merkle paths are non-trivial.
    let ticks = TableId::named("sys.stream_ticks");
    let answers = TableId::named("contract.answers");
    store.create_table(ticks);
    store.create_table(answers);

    for i in 0..64u64 {
        let mut key = Vec::with_capacity(40);
        key.extend_from_slice(&[7u8; 32]); // fake stream id
        key.extend_from_slice(&i.to_be_bytes());
        store.insert(ticks, key, (6_150_000u64 + i).to_le_bytes().to_vec());
    }
    store.insert(answers, b"sum".to_vec(), 55u64.to_le_bytes().to_vec());
    store.insert(answers, b"life".to_vec(), 42u64.to_le_bytes().to_vec());

    let store_root = store.store_root();

    // Prove a spread of keys across both tables.
    let mut wanted: Vec<(TableId, Vec<u8>)> =
        vec![(answers, b"sum".to_vec()), (answers, b"life".to_vec())];
    for i in [0u64, 1, 31, 63] {
        let mut key = Vec::with_capacity(40);
        key.extend_from_slice(&[7u8; 32]);
        key.extend_from_slice(&i.to_be_bytes());
        wanted.push((ticks, key));
    }

    let reads: Vec<_> = wanted
        .into_iter()
        .map(|(table, key)| {
            let read = store.prove_read(table, &key).expect("key present");
            assert!(read.verify(&store_root), "rust must verify its own proof");
            json!({
                "table": hex::encode(read.table.0 .0),
                "key": hex::encode(&read.key),
                "value": hex::encode(&read.value),
                "tableRoot": hex::encode(read.table_root.0),
                "rowProof": {
                    "siblings": read.row_proof.siblings.iter()
                        .map(|h| hex::encode(h.0)).collect::<Vec<_>>(),
                },
                "storeProof": {
                    "leafIndex": read.store_proof.leaf_index,
                    "siblings": read.store_proof.siblings.iter()
                        .map(|h| hex::encode(h.0)).collect::<Vec<_>>(),
                },
            })
        })
        .collect();

    let doc = json!({
        "_comment": "Generated by `cargo run -p peregrine-node --example gen_js_fixture`. \
                     Real proofs from the Rust implementation; the TS verifier must agree.",
        "storeRoot": hex::encode(store_root.0),
        "reads": reads,
    });

    let out = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../sdk/js/test/fixtures/proven-read.json");
    std::fs::create_dir_all(out.parent().expect("has parent"))?;
    std::fs::write(&out, serde_json::to_string_pretty(&doc)? + "\n")?;
    println!(
        "wrote {} proofs to {}",
        doc["reads"].as_array().unwrap().len(),
        out.display()
    );
    Ok(())
}
