//! Generate the session-signing fixture the JS SDK is tested against.
//!
//! The TypeScript SDK has to reproduce Rust's **bincode** encoding exactly, or
//! the signatures it produces are rejected by every validator — with no useful
//! error, because a bad signature and a bad encoding look identical from the
//! outside. One wrong length prefix is enough.
//!
//! So this emits, for a fixed seed:
//!
//! * the exact bytes `signing_bytes()` produces, and
//! * the signature Rust makes over them.
//!
//! ed25519 is deterministic (RFC 8032): the same key over the same message
//! always yields the same 64 bytes. A TypeScript signature that matches this
//! one byte-for-byte is therefore proof that the encoding underneath it is
//! correct — a much stronger check than "it verified".
//!
//! Run: `cargo run -p peregrine-node --example gen_session_fixture`

use peregrine_core::Keypair;
use peregrine_data::sessions::{
    Action, Scope, SessionAction, SessionGrant, ACTION_DOMAIN, GRANT_DOMAIN, REVOKE_DOMAIN,
};
use peregrine_data::streams::StreamId;
use peregrine_data::tables::TableId;
use serde_json::{json, Value};
use std::path::PathBuf;

fn hex(b: &[u8]) -> String {
    hex::encode(b)
}

fn main() -> anyhow::Result<()> {
    // Fixed seeds: the fixture must be byte-identical on every run, or the
    // TypeScript test would be chasing a moving target.
    let principal = Keypair::from_bytes(&[1u8; 32]);
    let agent = Keypair::from_bytes(&[2u8; 32]);
    let payee = Keypair::from_bytes(&[3u8; 32]);
    let oracle = Keypair::from_bytes(&[4u8; 32]);

    // A scope with two tables and one stream, so the `Vec` length prefixes are
    // actually exercised — a single-element scope would pass even if the prefix
    // were the wrong width.
    let t1 = TableId::named("agent.notes");
    let t2 = TableId::named("rwa.registry");
    let stream = StreamId::derive("acme/BTC-USD", &oracle.public());

    let grant = SessionGrant {
        principal: principal.public(),
        session_key: agent.public(),
        scope: Scope {
            tables: vec![t1, t2],
            streams: vec![stream],
            max_spend_per_action: 5,
        },
        budget_grains: 50,
        expires_at_round: 100,
        grant_nonce: 7,
    };
    let grant_bytes = grant.signing_bytes();
    let session_id = grant.id();
    let grant_sig = principal.sign(GRANT_DOMAIN, &grant_bytes);

    // Every action variant, so the enum tag width and each payload shape are
    // covered. A fixture that only exercised one variant would let a wrong tag
    // encoding through for the other three.
    let actions = vec![
        (
            "write",
            Action::Write {
                table: t1,
                key: b"title".to_vec(),
                value: b"PROP-1729".to_vec(),
            },
        ),
        (
            "pay",
            Action::Pay {
                payee: payee.public(),
                amount: 3,
            },
        ),
        (
            "subscribe",
            Action::Subscribe {
                stream,
                price_per_record: 2,
            },
        ),
        ("unsubscribe", Action::Unsubscribe { stream }),
    ];

    let encoded_actions: Vec<Value> = actions
        .into_iter()
        .enumerate()
        .map(|(i, (name, action))| {
            let sa = SessionAction {
                session_id,
                nonce: i as u64,
                action,
            };
            let bytes = sa.signing_bytes();
            let sig = agent.sign(ACTION_DOMAIN, &bytes);
            json!({
                "name": name,
                "nonce": i,
                "signingBytes": hex(&bytes),
                "signature": hex(&sig.0),
            })
        })
        .collect();

    let revoke_sig = peregrine_data::sessions::sign_revocation(&principal, &session_id);

    let doc = json!({
        "_comment": "Generated by `cargo run -p peregrine-node --example gen_session_fixture`. \
                     The TypeScript SDK must reproduce `signingBytes` byte-for-byte and produce \
                     identical signatures (ed25519 is deterministic).",
        "domains": {
            "grant": String::from_utf8_lossy(GRANT_DOMAIN),
            "action": String::from_utf8_lossy(ACTION_DOMAIN),
            "revoke": String::from_utf8_lossy(REVOKE_DOMAIN),
        },
        "keys": {
            "principalSeed": hex(&[1u8; 32]),
            "principalPublic": hex(&principal.public().0),
            "agentSeed": hex(&[2u8; 32]),
            "agentPublic": hex(&agent.public().0),
            "payeePublic": hex(&payee.public().0),
        },
        "grant": {
            "principal": hex(&grant.principal.0),
            "sessionKey": hex(&grant.session_key.0),
            "scope": {
                "tables": [hex(&t1.0 .0), hex(&t2.0 .0)],
                "streams": [hex(&stream.0 .0)],
                "maxSpendPerAction": 5,
            },
            "budgetGrains": 50,
            "expiresAtRound": 100,
            "grantNonce": 7,
            "signingBytes": hex(&grant_bytes),
            "sessionId": hex(&session_id.0),
            "signature": hex(&grant_sig.0),
        },
        "actions": encoded_actions,
        "revocation": {
            "sessionId": hex(&session_id.0),
            "signature": hex(&revoke_sig.0),
        },
    });

    let out =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../sdk/js/test/fixtures/sessions.json");
    std::fs::create_dir_all(out.parent().expect("has parent"))?;
    std::fs::write(&out, serde_json::to_string_pretty(&doc)? + "\n")?;

    println!(
        "wrote grant ({} bytes) + {} actions to {}",
        grant_bytes.len(),
        doc["actions"].as_array().unwrap().len(),
        out.display()
    );
    Ok(())
}
