//! Generate a cross-language fixture for oracle feeds.
//!
//! Registers a 3-source median price feed, publishes real signed observations,
//! and emits a proven read of `sys.feed_latest` to
//! `sdk/js/test/fixtures/feed.json`, so the TypeScript feed decoder is checked
//! byte-for-byte against the Rust implementation.
//!
//! Run: `cargo run -p peregrine-node --example gen_feed_fixture`

use peregrine_core::Keypair;
use peregrine_data::feeds::{
    feed_latest_table, Aggregation, FeedKind, FeedPublisher, FeedSpec, FeedValue,
};
use peregrine_data::tables::{ProvenRead, RowProof};
use peregrine_node::payload::WirePayload;
use peregrine_node::pipeline::ExecutionPipeline;
use serde_json::{json, Value};

fn row_proof_json(p: &RowProof) -> Value {
    let siblings: Vec<String> = p.siblings().iter().map(|h| hex::encode(h.0)).collect();
    match p {
        RowProof::V1(_) => json!({ "siblings": siblings }),
        RowProof::V2(v2) => json!({
            "siblings": siblings,
            "otherLeaf": v2.other_leaf.as_ref().map(|(k, val)| json!({
                "key": hex::encode(k), "value": hex::encode(val),
            })),
        }),
    }
}

fn proven_read_json(read: &ProvenRead) -> Value {
    json!({
        "table": hex::encode(read.table.0 .0),
        "key": hex::encode(&read.key),
        "value": hex::encode(&read.value),
        "tableRoot": hex::encode(read.table_root.0),
        "treeVersion": read.row_proof.version().as_str(),
        "rowProof": row_proof_json(&read.row_proof),
        "storeProof": {
            "leafIndex": read.store_proof.leaf_index,
            "siblings": read.store_proof.siblings.iter().map(|h| hex::encode(h.0)).collect::<Vec<_>>(),
        },
    })
}

fn main() {
    let keys = [
        Keypair::from_bytes(&[201; 32]),
        Keypair::from_bytes(&[202; 32]),
        Keypair::from_bytes(&[203; 32]),
    ];
    let spec = FeedSpec {
        channel: "price/BTC-USD".into(),
        kind: FeedKind::Price,
        decimals: 2,
        aggregation: Aggregation::Median,
        providers: keys.iter().map(|k| k.public()).collect(),
        max_staleness_rounds: 5,
    };

    let mut node = ExecutionPipeline::new();
    let feed_id = node.register_feed(spec.clone());
    let mut pubs: Vec<FeedPublisher> = keys
        .into_iter()
        .map(|k| FeedPublisher::new(&spec, k))
        .collect();

    let updated_round = 5u64;
    node.set_round_for_test(updated_round);
    for (i, price) in [6_150_000u64, 6_151_000, 6_149_000].iter().enumerate() {
        node.apply_payload(&WirePayload::Shred(pubs[i].observe_at(*price, 0)));
    }

    let store_root = node.store_root();
    let read = node
        .prove_read(feed_latest_table(), &feed_id.0 .0)
        .expect("feed value present");
    assert!(read.verify(&store_root), "rust verifies its own feed proof");
    let fv = FeedValue::decode(&read.value).expect("decodes");

    let out = json!({
        "_comment": "Generated by `cargo run -p peregrine-node --example gen_feed_fixture`. \
                     A real median price-feed value + proof from the Rust node; the TS decoder must agree.",
        "storeRoot": hex::encode(store_root.0),
        "feedId": hex::encode(feed_id.0 .0),
        "read": proven_read_json(&read),
        "nowRound": 7,               // within staleness of updatedRound 5
        "staleRound": 20,            // beyond max_staleness 5
        "maxStalenessRounds": spec.max_staleness_rounds,
        "expected": {
            "value": fv.value,
            "decimals": fv.decimals,
            "kind": fv.kind.code(),
            "aggregation": fv.aggregation.code(),
            "nSources": fv.n_sources,
            "updatedRound": fv.updated_round,
        },
    });
    let text = serde_json::to_string_pretty(&out).unwrap() + "\n";
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../sdk/js/test/fixtures/feed.json"
    );
    std::fs::create_dir_all(std::path::Path::new(path).parent().unwrap()).unwrap();
    std::fs::write(path, &text).unwrap();
    eprintln!("wrote {path} ({} bytes)", text.len());
}
