/**
 * Hashing primitives — an exact mirror of the Rust implementation.
 *
 * Every constant and byte layout here must match `peregrine-core` and
 * `peregrine-data` precisely, or proofs generated by a node will not verify in
 * the browser. The cross-language fixture test (`test/verify.test.ts`) exists
 * to keep the two honest: it checks real node-produced proofs against this
 * code.
 */
import { blake3 } from "@noble/hashes/blake3";

export type Bytes = Uint8Array;

const enc = new TextEncoder();

/** Domain tags (mirror of the Rust `*_DOMAIN` constants). */
const D_MERKLE_NODE = enc.encode("peregrine.merkle.node.v1");
const D_MERKLE_LEAF = enc.encode("peregrine.merkle.leaf.v1");
const D_SMT_LEAF = enc.encode("peregrine.smt.leaf.v1");
const D_SMT_EMPTY = enc.encode("peregrine.smt.empty.v1");

/** Depth of the sparse Merkle tree = bits in a position hash. */
export const SMT_DEPTH = 256;

/** BLAKE3 over the concatenation of `parts` (`Hash::digest` when given one part). */
export function digest(...parts: Bytes[]): Bytes {
  const h = blake3.create();
  for (const p of parts) h.update(p);
  return h.digest();
}

/** Domain-separated interior node: `Hash::combine`. */
export function combine(left: Bytes, right: Bytes): Bytes {
  return digest(D_MERKLE_NODE, left, right);
}

/** Binary-Merkle leaf hash (`merkle::leaf_hash`). */
export function merkleLeafHash(bytes: Bytes): Bytes {
  return digest(D_MERKLE_LEAF, bytes);
}

/** Occupied SMT leaf, binding key *and* value (`smt::leaf_hash`). */
export function smtLeafHash(key: Bytes, value: Bytes): Bytes {
  return digest(D_SMT_LEAF, u32le(key.length), key, u32le(value.length), value);
}

/** The empty-slot leaf constant (`smt::empty_leaf`). */
export function smtEmptyLeaf(): Bytes {
  return digest(D_SMT_EMPTY);
}

/** The i-th bit of a 32-byte position, MSB of byte 0 first. */
export function bit(h: Bytes, i: number): number {
  return (h[i >> 3] >> (7 - (i & 7))) & 1;
}

function u32le(n: number): Bytes {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, n, true);
  return b;
}

// ── hex helpers ─────────────────────────────────────────────────────────────

export function fromHex(hex: string): Bytes {
  const s = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (s.length % 2 !== 0) throw new Error(`odd-length hex string: ${s.length}`);
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) {
    const byte = Number.parseInt(s.substr(i * 2, 2), 16);
    if (Number.isNaN(byte)) throw new Error(`invalid hex at byte ${i}`);
    out[i] = byte;
  }
  return out;
}

export function toHex(bytes: Bytes): string {
  let s = "";
  for (const b of bytes) s += b.toString(16).padStart(2, "0");
  return s;
}

export function bytesEqual(a: Bytes, b: Bytes): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

export function concat(...parts: Bytes[]): Bytes {
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const p of parts) {
    out.set(p, off);
    off += p.length;
  }
  return out;
}

/** Read a little-endian u64 from the first 8 bytes (values are LE-encoded). */
export function readU64LE(bytes: Bytes): bigint {
  if (bytes.length < 8) throw new Error(`need 8 bytes, got ${bytes.length}`);
  return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getBigUint64(0, true);
}
